function [fitresult, gof] = createFit(f, V)
%CREATEFIT(F,V)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : f
%      Y Output: V
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Jul-2022 22:33:55


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( f, V );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.211655668425166;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'V vs. f', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'f', 'Interpreter', 'none' );
ylabel( 'V', 'Interpreter', 'none' );
grid on


